http://www.omdbapi.com/?apikey=c91e9192&s=asdasdasdsadsad
# ternyata selama ini kita bisa pake rest client di vscode tanpa buka aplikasi lain speerti postman :(
# cara nya dengan mendowload extension rest client , dan cara menggunakan nya kita harus punya file dengan extensn http